language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pipenv install --dev
# command to run tests
script:
  - pytest --cov-report term  --cov=./back
after_success:
  - coveralls